### ISSUE TITLE
原来 CMU 不做 Simulator / Assembler Lab 呀……

### ISSUE THREAD

**Issue by hczhcz** [YeXiaoRain/ICS_LAB_CMU_2016#1]
RT，表示惊讶

**Comment by YeXiaoRain** [comment]
对`_(:з」∠)_`你看我们的pdf画风都不一样

还有新版memory我测的很多同学代码都爆了 以及最后proxy的要求好像也太不一样

**Comment by hczhcz** [comment]
有点意思

那个 Malloc 是真难，当年做得印象深刻

**Comment by YeXiaoRain** [comment]
orz 还打算整理CSE,OS,DS

但好像我自己的CSE都找不到了

还望橙汁大腿多多指导

**Comment by hczhcz** [comment]
CSE 似乎就是做出一个文件系统

lab 说明这里有：[CSE 2015](https://www.evernote.com/pub/unitial/cse-2015#st=p&n=fdc9eca4-54fa-4487-9c99-3cb15052767b)

实现可以看 MIT 6.033 的或者 [Awesome SE](https://github.com/SJTU-SE/awesome-se#cse-yfs-lab-mit-6033)

**Comment by YeXiaoRain** [comment]
:smiley:

**Comment by hczhcz** [comment]
感觉还是 ICS 的 lab 好玩 :D

**Comment by YeXiaoRain** [comment]
同感 种类繁多 + 测分程序有很多可用bug :laughing:
